/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.definitions;

import org.junit.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        
    }
}
